version: '{build}'

platform:
  - x64

clone_folder: C:\projects\brave-portable
test: off

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GOPATH: C:\gopath
  GOROOT: C:\go\
  GOVERSION: 1.11

install:
  - ps: choco install ant
  - ps: Install-Product node 8
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - cmd: SET PATH=%GOPATH%\bin;%GOPATH%\bin\windows_386;%GOROOT%bin;%PATH%
  - java -version
  - ant -version
  - node --version
  - npm --version
  - go version
  - go env

configuration:
  - Release

before_build:
  - git clone https://github.com/portapps/portapps C:\projects\portapps

build_script:
  - ant release

after_build:
  - ps: |
      $env:APP_VERSION = Get-Content C:\projects\brave-portable\bin\tmp\version.dat -Raw
      Write-Host "App version: $env:APP_VERSION"

artifacts:
  - path: 'bin\release\*'
    name: release

deploy:
  tag: $(APP_VERSION)
  release: $(APP_VERSION)
  description: 'New release: $(APP_VERSION)'
  provider: GitHub
  auth_token:
    secure: jFbo7oVnD9HZL5LL+nE0IC8x6xHlqvkeVDeMj/WS+Rk9GanjBKlnlvTjeHsNlo+/
  artifact: release
  draft: true
  prerelease: false
  on:
    branch: master

notifications:
  - provider: Webhook
    url:
      secure: 3V6QSptnPc6MYQn2S8/BzENJ5YDEn94VmCi2xmTCa0stiRA+hDKpyGaE0eVrW+sIhxIMoas74AE9613+5DVK/FyIFG40cSL1L4x+ePPe1Zm82NL2XMp5uS/G3M0vRPiBd+FOk7jEeAAQ+heUBXbFqw==
    method: post
